### PR TITLE
50ohm version of AXICOM HF3 relay

### PR DESCRIPTION
**Pull request by dejfson**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for your contribution.  We have a set of rules (the KLC) that footprints accepted into this lib have to follow. You can review them here:
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention
https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions

Please have a look at these rules and at the examples of existing symbols in the other libs. then try and make your symbol conform. What is required from having a quick peek:
1. add a silkscreen drawing that is visible AFTER assembly (on F.Silk)
2. add a courtyard with the correct spacing from the pad-outline and/or the package outline (on F.Fab)
3. Add a pin1-marker to both F.Fab and F.Silk
4. Add a standard-link to the 3D model even if it does not exist yet ... then the model will be displayed within KiCAD as soon as it becomes available
5. Does this footprint match any symbol in the schematic lib? If not, it would be great if you could provide a symbol.

Finally for future PR: Posting a short description, link to the datasheet and a screenshot of your new footprint makes the review process much easier and quicker for us.

best,
JAN

**Comment by jkriege2** [comment]
PS: Let me know if you need any further advice or help ...

**Comment by dejfson** [comment]
Ok, this is second attempt. Please have a look. As to the checks, it would be a great idea to update kicad-library-tools checking script such, that if certain layers are expected to be in the pcb file (as courtyyard or silk), that they are checked at least for a presence. A simple test of style: there has to be at least one line in courtyyard. This would avoid missing layers discussions. 

Please have a look at latest commit and let me know. Once this PR is merged, I will create exactly the same footprint, but for 75ohm version (they differ only by certain pad widths) and tomorrow I would create new schematic symbol for it.
screenshot_20170911_225700

**Comment by jkriege2** [comment]
OK!

looks mstly good to me now ... Only one thing to change before I can merge. We usually use now a camphered corner for pin1-mark on F.Fab (pin1-mark on Silkscreen is fine):
2017-08-21 21_14_51-footprint editor no active library

Could you change your pin1 accordingly?

Thanks,
JAN

PS: About the checks: The scripts are still under development (they are in the current form form a few months now only ... and we try to keep up with the development of KLCs ;-) ... so could you simply post a PR for such a feature (if you have time and feel fit enough in python), or simply open an issue, describing what you want in the repo of the utils? That would be great!

**Comment by dejfson** [comment]
Here it goes
screenshot_20170911_232151

If i forget to add some layers in the future, i'll try to make PR for python scripts to add additional checks on this :) Have to say, making footprint from scratch is quite complex and prone to errors

**Comment by jkriege2** [comment]
Yes it is ... note however that many footprints in this lib are nowadays made by scripts: https://github.com/pointhi/kicad-footprint-generator Maybe that helps you in the future ;-)

best & thanks for your contrib!
JAN

**Pull request merged**
